/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'plazasModel',
        'loginStore',
        'usuariosModel',
        'permisosModel',
        'permisosLoginModel',
        'programasModel',
        'conceptosModel',
        'detallesModel',
        'estadoCuentaDetallesModel',
        'estadoResultadoModel',
        'detallePorcentModel',
        'companiasModel',
        'estadoResultadoConfiguracionModel',
        'mesEstadoResultadoConfiguracionModel',
        'anioEstadoResultadoConfiguracionModel',
        'empleadosModel',
        'emisionesPorProgramaModel',
        'programasEmpleadosModel',
        'claveCompaniasModel',
        'cmbPlazaEmpleadoModel'
    ],
    stores: [
        'plazasStore',
        'loginStore',
        'usuariosStore',
        'permisosStore',
        'permisosLoginStore',
        'programasStore',
        'conceptosStore',
        'detallesStore',
        'estadoCuentaDetallesStore',
        'estadoResultadosStore',
        'detallePorcentStore',
        'companiasStore',
        'cmbPlazaStore',
        'estadoResultadoConfiguracionStore',
        'mesesEstadoResultadoConfiguracionStore',
        'anioEstadoResultadoConfiguracionStore',
        'empleadosStore',
        'tiposCostosStore',
        'completoParcialStore',
        'emisionesPorProgramaStore',
        'programasEmpleadosStore',
        'claveCompaniaStore',
        'cmbPlazaEmpleadoStore'
    ],
    views: [
        'loginView',
        'MainView',
        'panelUsuarios',
        'windowNewUsuario',
        'windowEditUsuario',
        'panelProgramas',
        'windowNewProgramas',
        'windowEditProgramas',
        'panelPlazas',
        'windowNewPlazas',
        'windowEditPlazas',
        'panelConceptos',
        'windowNewConceptos',
        'windowEditConceptos',
        'panelDetalles',
        'windowNewDetalles',
        'windowEditDetalles',
        'panelEstadoResultado',
        'windowEditEstadoResultadoDetalles',
        'panelpresentacion',
        'panelCompanias',
        'windowEstadoResultadoConfiguracion',
        'panelEmpleados',
        'windowEditEmpleados',
        'windowEmisionPorProgramaMes',
        'windowNewClaveCompania',
        'windowEditClaveCompania'
    ],
    name: 'tvp',

    launch: function() {
        Ext.create('tvp.view.loginView');
    }

});
